#!/usr/bin/env bash
set -e

# don't change these 4 lines
SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
TRAINING=$1;
INPUT=$2;
OUTPUT=$3;

train_trees_pre="train.trees.pre"
train_trees_pre_unk="train.trees.pre.unk"
dev_parses="dev.parses"
python preprocess.py $TRAINING > $train_trees_pre
python unknown.py $train_trees_pre > $train_trees_pre_unk
python AP_HW4.py "$train_trees_pre_unk" "$INPUT" "$dev_parses"
python postprocess.py $dev_parses >  "$OUTPUT"
echo "DONE !!!"